[package]
name = "adventofcode"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
glam = { version = "0.29.2", features = ["glam-assert"] }
petgraph = "0.6"
regex = "1.11.1"
unicode-width = { version = "0.2.0", default-features = false }
